### ISSUE TITLE
Does it work with slides of varying sizes?

### ISSUE THREAD

**Issue by tnrich** [jl-/react-slide-deck#1]
My slides are of varying sizes, will that be an issue if using this library. I'm having a bit of difficulty getting the positioning to work just right... Thanks!

**Comment by jl-** [comment]
Thanks for trying this out, but sorry, it doesn't support that. `Slide`s are of the same height and width as their container `Deck`. For your case,  [react-slick](https://github.com/akiran/react-slick) may be a better choice, which support variable width and Adaptive height.

**Comment by tnrich** [comment]
Hmm okay thanks for the tip. What are the technical reasons why the decks
can't be scrolled with items of variable heights?

**Comment by jl-** [comment]
@tnrich Ha, just for simplicity. I create it for one page scrolling (in my case, there is no scrolling consideration). I just released a new version`0.0.9`, which support scrolling now. If the content within a `Slide` overflows, the `Deck` will not switch to the next/pre `Slide` until you scroll to the bottom/top of the current `Slide`. [see the DEMO](http://output.jsbin.com/hexada) here, the content on the `three` tab is overflow, scroll down and you will see it. However, the detection for scroll is simple and may not cover the horizontal scrolling, If you have such need, please let me know if I could help. PR would be greatly appreciated

**Comment by tnrich** [comment]
hey @jl- thanks for getting in touch. Ideally what I'd like is a way to have a normal horizontal slide deck, but allow the slides themselves to be of variable heights. I'd be happy to make a PR, but I'm not quite sure where to start with it.. do you have any ideas for how one might enable this functionality? As I see it, the issue arises because multiple slides are being displayed at a time on the page, and there is no simple way to bound the height of one (if for example it has less content and takes up less height), without bounding the height of the other slides.

**Comment by jl-** [comment]
> for example it has less content and takes up less height

The basic strategy adopted here is to make all the `Slide`s absolute positioned and of the same size as the `Deck`. 
Based on this strategy, for `Slides` with less content, they still take up 100% height, which from my point of view makes more sense: Say if we support varying height, then for `Slide`s with less height, there are cases that somebody wants to vertical-centered those `Slide`s while others want them to be top-aligned with the `Deck` ..., also it's complicated for supporting swiping. 

However, if you're  satisfied with current implement and want `Slide`s with overflow content to be scrollable, which I tried to support on v0.0.10 with the following strategy(not well supported yet):
- Implement a `isCurrentSlideScrolling(event)` function on `Deck` instance, in this function, you can access the current `Slide` instance, then you can detect if it is scrolling. see [this rough attempt](https://github.com/jl-/react-slide-deck/blob/master/src/deck.js#L126)
- call `isCurrentSlideScrolling` function to test if the current slide is scrolling on `handleWheel` and `handleSwipeMove` function, if the current slide is scrolling, then let it be, and do not perform a `Slide` tweening transition.

I will make a refactor as soon as possible, currently busy with schooling. sorry for that.  And thx!

**Comment by jl-** [comment]
Hi, @tnrich, I just released v0.1.0, fixed some major problems, including swiping and scrolling. Still, `Slide` is 100% width and 100% height, but if your content overflows, users can scroll now. If you're still interested, please see the [DEMO](http://output.jsbin.com/hexada).

**Comment by tnrich** [comment]
Awesome work I'll check it out. Thanks!
