### ISSUE TITLE
Swipe before end.

### ISSUE THREAD

**Issue by razvanip** [jl-/react-slide-deck#2]
Would be nice if u could continue swipeing even if the current swipe did not finish.

**Comment by jl-** [comment]
Currently you can perform a new swipe action during the canceling. Maybe I disable that for a confirmed swipe [here](https://github.com/jl-/react-slide-deck/blob/master/src/deck.js#L157), yeah, I think we need it. Will look into that when I wake up tomorrow.

**Comment by jl-** [comment]
Hi, @razvanip, here is a new released 0.0.10. Open the  [DEMO](http://output.jsbin.com/hexada) on mobile phone and you can see if that works for you.

**Comment by razvanip** [comment]
:+1:  great
