### ISSUE TITLE
Possible to add slide dynamically?

### ISSUE THREAD

**Issue by oertels** [jl-/react-slide-deck#8]
I'm trying to add a slide under certain circumstances in the render method, but on insertion, I get:

```
invariant.js:38 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.
```

**Comment by jl-** [comment]
Hi, @schneck, could you please provide some more details(code maybe)? How you made the insertion?

**Comment by oertels** [comment]
hi, I'm inserting it within the `render()` method using a map. untested example:

```
render() {
    <Deck>
      {mylist.map(item =>
         <Deck.Slide [...] />
      )}
    </Deck>
}

```

**Comment by jl-** [comment]
@schneck Sorry for the late reply, but it seems that's not the problem with  react-deck-slide, I made a [demo](http://jsbin.com/xoxoju/edit?js,output) here.
