### ISSUE TITLE
Horizontal Wheel/Scroll Event

### ISSUE THREAD

**Issue by ankitduseja** [jl-/react-slide-deck#9]
I want to make the component react to horizontal scroll events (left or right) in a similar fashion as it responds to vertical wheel event currently. This enables a two finger horizontal swipe gesture on mousepads (in macs or the laptops that support it). This didn't seem to work in the attached demo. Is this currently supported?

A separate prop to enable/disable this event would make sense.

**Comment by jl-** [comment]
Hi @ankitduseja , I'm not sure if I've understood you correctly, you can check out [this demo](http://jl-.github.io/react-slide-deck/) to see if that's the feature you want: click the 'Horizontal' button on the left bottom of the demo page, and then see the third Slide, it's scrollable

**Comment by ankitduseja** [comment]
Hi @jl- It seems to be working in the updated demo link you posted. Closing this issue!
